version: '2'
services:
  monolith-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: monolith-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  monolith-kafka:
    image: confluentinc/cp-kafka:latest
    container_name: monolith-kafka
    depends_on:
      - monolith-zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: monolith-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://monolith-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "user_features:1:1"

volumes:
  monolith_data: